// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhjztcbgwghbvcmjoheu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoanp0Y2Jnd2doYnZjbWpvaGV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTExMzgsImV4cCI6MjA2NjI4NzEzOH0.cGw_vwZf5cK_uq08__lYcrPc7TPgS2vkcBh8_88taQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);